### ISSUE TITLE
Ryan add me as a contributor

### ISSUE THREAD

**Issue by TotallyNotVirtIO** [Ryans-MC-Computer-Mods-Projects/OC2S#1]
do it

**Comment by TotallyNotVirtIO** [comment]
ryan when are you gonna do it

**Comment by TotallyNotVirtIO** [comment]
@Ryans-MC-Computer-Mods-Projects

**Comment by TotallyNotVirtIO** [comment]
ryaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaan

**Comment by Ryans-MC-Computer-Mods-Projects** [comment]
Hi

**Comment by TotallyNotVirtIO** [comment]
add me as a contributor

**Comment by TotallyNotVirtIO** [comment]
ryan it doenst take that long

**Comment by TotallyNotVirtIO** [comment]
ryaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaan

**Comment by Ryans-MC-Computer-Mods-Projects** [comment]
Done

**Comment by TotallyNotVirtIO** [comment]
good

**Comment by TotallyNotVirtIO** [comment]
you didnt
![image](https://user-images.githubusercontent.com/78849100/162586446-310cf744-6f04-41fe-b333-44c0684cb2e9.png)

**Comment by TotallyNotVirtIO** [comment]
just add my ssh key
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL7yAU68rhx1AGhts7AMWhWAi5T+WPGdZhUfSXvFDiPM tobich228@gmail.com

**Comment by TotallyNotVirtIO** [comment]
email leak idc

**Comment by Ryans-MC-Computer-Mods-Projects** [comment]
![image](https://user-images.githubusercontent.com/99054441/162586500-fdf9c925-face-475f-bc06-59bb2e33ffce.png)

**Comment by TotallyNotVirtIO** [comment]
nvm im retarted
